const assert=require('node:assert/strict')
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright')
async function main(){
  const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true})
  const page=await browser.newPage({viewport:{width:1440,height:1000}})
  page.setDefaultTimeout(5000)
  const errors=[],writes=[],discoveries=[],broadcasts=[]
  page.on('pageerror',error=>errors.push(error.message))
  let style='standard',mode='valid',failSettings=false,failSave=false,release
  const deferred=()=>new Promise(resolve=>{release=resolve})
  let service={id:1,name:'Emby',url:'https://media.example.com/',icon:null,category:'影音',description:'fixture',sort:0,public:true,enabled:true,checkEnabled:true,status:'unknown',responseMs:null,checkedAt:null,createdAt:1,updatedAt:2}
  await page.exposeFunction('recordAppearance',message=>broadcasts.push(message))
  await page.addInitScript(()=>{const channel=new BroadcastChannel('navigation-appearance');channel.onmessage=event=>window.recordAppearance(event.data)})
  await page.route('https://**/*',route=>route.fulfill({status:404,body:''}))
  await page.route('**/api/**',async route=>{
    const request=route.request(),path=new URL(request.url()).pathname
    const send=value=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)})
    if(path==='/api/me')return send({authed:true,github:false,site_name:'Guide',public_page:true})
    if(path==='/api/services/discover-icon'){
      discoveries.push(request.postDataJSON())
      if(mode==='pending')await deferred()
      if(mode==='fail')return route.fulfill({status:400,contentType:'text/plain',body:'网站图标获取失败，请检查地址或网络'})
      if(mode==='empty')return send({icons:[]})
      return send({icons:[{name:'icon',url:'https://images.example.com/icon.png'},{name:'apple-touch-icon',url:'https://images.example.com/touch.png'},{name:'favicon.ico',url:'https://media.example.com/favicon.ico'}]})
    }
    if(path==='/api/services'&&request.method()==='GET')return send([service])
    if(path==='/api/services/1'){const values=request.postDataJSON();writes.push({path,values});service={...service,...values};return send(service)}
    if(path==='/api/settings'){
      if(request.method()==='GET')return failSettings?route.fulfill({status:503,contentType:'text/plain',body:'外观读取失败'}):send({service_card_style:style,site_name:'Guide',retention_days:'30',public_page:'on',icon_libraries:JSON.stringify({activeId:'',libraries:[]})})
      if(failSave)return route.fulfill({status:400,contentType:'text/plain',body:'外观保存失败'})
      const values=request.postDataJSON();writes.push({path,values});assert.deepEqual(Object.keys(values),['service_card_style']);style=values.service_card_style;return send({ok:true})
    }
    throw new Error(`Unexpected API ${path}`)
  })
  const form=()=>page.getByRole('dialog',{name:'编辑服务',exact:true})
  const dialog=()=>page.getByRole('dialog',{name:'获取网站图标',exact:true})
  const open=()=>form().getByRole('button',{name:'获取网站图标',exact:true}).click()
  const edit=()=>page.getByRole('button',{name:'编辑 Emby',exact:true}).click()
  try{
    await page.goto((process.env.SERVICE_ADMIN_PREVIEW||'http://127.0.0.1:5201')+'/admin/services')
    await page.locator('header').getByRole('link',{name:'Guide',exact:true}).waitFor()
    assert.equal(await page.title(),'Guide 后台')
    await edit()
    assert.equal(discoveries.length,0)
    await form().getByLabel('URL',{exact:true}).fill('https://changed.example.com/')
    assert.equal(discoveries.length,0,'URL editing must not discover automatically')
    await form().getByLabel('URL',{exact:true}).fill('')
    await open();await form().getByRole('alert').filter({hasText:'请先填写网站 URL'}).waitFor()
    assert.equal(discoveries.length,0)
    await form().getByLabel('URL',{exact:true}).fill('https://media.example.com/')
    mode='pending';await open()
    await dialog().getByRole('status').filter({hasText:'正在获取'}).waitFor()
    await dialog().getByRole('button',{name:'取消',exact:true}).click()
    release();mode='valid'
    assert.equal(writes.length,0)
    await open()
    await dialog().locator('[data-discovered-icon]').first().waitFor()
    assert.equal(await dialog().locator('[data-discovered-icon]').count(),3)
    await dialog().getByRole('button',{name:/apple-touch-icon/}).click()
    await dialog().getByRole('button',{name:'使用此图标',exact:true}).click()
    assert.equal(await form().getByLabel('图标',{exact:true}).inputValue(),'https://images.example.com/touch.png')
    assert.equal(writes.length,0,'confirmation fills field only')
    await form().getByRole('button',{name:'保存',exact:true}).click();await form().waitFor({state:'hidden'})
    assert.equal(writes.at(-1).values.icon,'https://images.example.com/touch.png')
    await edit();mode='fail';await open()
    await dialog().getByRole('alert').filter({hasText:'获取失败'}).waitFor()
    mode='empty';await dialog().getByRole('button',{name:'重试',exact:true}).click()
    await dialog().getByText('没有找到安全的 HTTPS 图标候选，可使用图标库或手动填写。',{exact:true}).waitFor()
    await dialog().getByRole('button',{name:'取消',exact:true}).click()
    await form().getByLabel('图标',{exact:true}).fill('https://manual.example.com/a.png')
    await form().getByRole('button',{name:'保存',exact:true}).click();await form().waitFor({state:'hidden'})
    assert.equal(writes.at(-1).values.icon,'https://manual.example.com/a.png')
    await page.getByRole('button',{name:'设置',exact:true}).click()
    await page.getByRole('radio',{name:'标准卡片',exact:true}).waitFor()
    assert.equal(await page.getByRole('radio',{name:'标准卡片',exact:true}).isChecked(),true)
    await page.getByRole('radio',{name:'小卡片',exact:true}).check()
    failSave=true;await page.getByRole('button',{name:'保存卡片样式',exact:true}).click()
    await page.getByRole('alert').filter({hasText:'外观保存失败'}).waitFor()
    assert.equal(await page.getByRole('radio',{name:'小卡片',exact:true}).isChecked(),true)
    failSave=false;await page.getByRole('button',{name:'保存卡片样式',exact:true}).click()
    await page.waitForFunction(()=>document.querySelector('button')!==null)
    await page.getByText('卡片样式已保存，公开导航已生效',{exact:true}).waitFor()
    assert.equal(style,'compact')
    await page.waitForTimeout(100)
    assert.ok(broadcasts.some(message=>message.type==='refresh'))
    await page.reload();await page.getByRole('radio',{name:'小卡片',exact:true}).waitFor()
    assert.equal(await page.getByRole('radio',{name:'小卡片',exact:true}).isChecked(),true)
    for(const [label,value] of [['极简卡片','minimal'],['标准卡片','standard']]){
      await page.getByRole('radio',{name:label,exact:true}).check();await page.getByRole('button',{name:'保存卡片样式',exact:true}).click()
      await page.waitForTimeout(100);assert.equal(style,value)
    }
    failSettings=true;await page.reload()
    await page.getByRole('alert').filter({hasText:'外观读取失败'}).waitFor()
    failSettings=false;await page.getByRole('button',{name:'重试加载',exact:true}).click()
    await page.getByRole('radio',{name:'标准卡片',exact:true}).waitFor()
    await page.evaluate(()=>document.documentElement.classList.add('dark'))
    await page.setViewportSize({width:390,height:844})
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
    assert.deepEqual(errors,[])
    console.log('PASS v3.3 admin: manual discovery/no auto request/loading/cancel/preview/confirmation/no implicit save/error Retry/empty/manual fallback; appearance default/three values/save error draft/reload persistence/BroadcastChannel/read retry/dark/mobile. Test-layer APIs/images only.')
  }finally{await browser.close()}
}
main().catch(error=>{console.error(error);process.exitCode=1})
